id: '1737842400000'
name: Bathing
entities:
  light.bathroom_strip:
    state: 'on'
    brightness: 32
    hs_color: [340, 50]
  light.bathroom_lamp:
    state: 'on'
    brightness: 32
    hs_color: [340, 50]
metadata: {}
